export const SKILLS_DATA = [
  {
    id: '1',
    skillId: 'find-skills',
    name: 'find-skills',
    installs: 774858,
    source: 'vercel-labs/skills',
    selected: true,
  },
  {
    id: '2',
    skillId: 'vercel-react-best-practices',
    name: 'vercel-react-best-practices',
    installs: 261140,
    source: 'vercel-labs/agent-skills',
    selected: true,
  },
  {
    id: '3',
    skillId: 'web-design-guidelines',
    name: 'web-design-guidelines',
    installs: 210642,
    source: 'vercel-labs/agent-skills',
    selected: false,
  },
  {
    id: '4',
    skillId: 'vercel-composition-patterns',
    name: 'vercel-composition-patterns',
    installs: 106235,
    source: 'vercel-labs/agent-skills',
    selected: true,
  },
  {
    id: '5',
    skillId: 'agent-browser',
    name: 'agent-browser',
    installs: 140448,
    source: 'vercel-labs/agent-browser',
    selected: false,
  },
  {
    id: '6',
    skillId: 'vercel-react-native-skills',
    name: 'vercel-react-native-skills',
    installs: 75233,
    source: 'vercel-labs/agent-skills',
    selected: false,
  },
  {
    id: '7',
    skillId: 'next-best-practices',
    name: 'next-best-practices',
    installs: 47761,
    source: 'vercel-labs/next-skills',
    selected: false,
  },
  {
    id: '8',
    skillId: 'deploy-to-vercel',
    name: 'deploy-to-vercel',
    installs: 17714,
    source: 'vercel-labs/agent-skills',
    selected: false,
  },
  {
    id: '9',
    skillId: 'dogfood',
    name: 'dogfood',
    installs: 15246,
    source: 'vercel-labs/agent-browser',
    selected: false,
  },
  {
    id: '10',
    skillId: 'ai-sdk',
    name: 'ai-sdk',
    installs: 14525,
    source: 'vercel/ai',
    selected: false,
  },
]

export const ALWAYS_INCLUDED_AGENTS = [
  'Amp',
  'Antigravity',
  'Cline',
  'Codex',
  'Cursor',
  'Deep Agents',
  'Gemini CLI',
  'GitHub Copilot',
  'Kimi Code CLI',
  'OpenCode',
  'Replit',
  'Warp',
]

export const ADDITIONAL_AGENTS = [
  { name: 'Augment', selected: false },
  { name: 'Claude Code', selected: true },
  { name: 'CodeBuddy', selected: false },
  { name: 'Command Code', selected: false },
  { name: 'Continue', selected: false },
  { name: 'Cortex Code', selected: false },
  { name: 'Crush', selected: false },
  { name: 'Goose', selected: false },
  { name: 'Junie', selected: false },
  { name: 'Kilo Code', selected: false },
  { name: 'Kiro CLI', selected: false },
  { name: 'Mistral Vibe', selected: false },
  { name: 'OpenClaw', selected: false },
  { name: 'OpenHands', selected: false },
  { name: 'Roo Code', selected: false },
  { name: 'Trae', selected: false },
  { name: 'Windsurf', selected: true },
  { name: 'Zencoder', selected: false },
]
